### ISSUE TITLE
Correct Example (Quick)

### ISSUE THREAD

**Issue by Salim9304** [fluffykoalas/sloth#12]
Correct Example (Quick)
Now so
```
from sloth.simple import time_callable
import time

def my_func(a, b, c):
    time.sleep(1)
    print(a, b, c)
(time_callable(my_func, 2, 'a', 'b', 'c'))
```
> a b c
> a b c
```
The example is expected like this
a b c
1.000063419342041
```

fix example:
(time_callable(my_func, 2, 'a', 'b', 'c')) ----> print(time_callable(my_func, 2, 'a', 'b', 'c'))

> a b c
> a b c
> 1.000063419342041

**Comment by Legorooj** [comment]
The example was only slightly off, and was intended to be run from a python shell, not a script, so no print call is used.
